Footer overlapping "Presentation" block issue
iLiveMyLife/iLiveMyLife.io pull request #14
Opened 2021-12-15 01:49 UTC by dwin199601

To fix the footer overlapping of the Presentation block I've changed position from absolute on a relative in footer-style class, in app.css file.  Now, the "send email" message is located properly under the main block

2021-12-15 22:27 UTC, silarr requested changes

2021-12-15 22:27 UTC, silarr commented on package-lock.json
> -      "integrity": "sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==",
ну вот не пойму что эти строчки делают. Если я прийму пулл реквест, то не ясно что поменяется. Может откатить этот файл, чтобы не путать?

2021-12-15 22:27 UTC, silarr commented on package-lock.json
> +  "name": "i-live-my-life-landing-client",
хорошая штука

2021-12-15 22:27 UTC, silarr commented on src/app/App.css
> +  transition-property: font-size;
мне понравилось, я даже у себя запустил и сравнил. Работает вроде красиво! Молодец!

2021-12-16 19:00 UTC, dwin199601 commented on package-lock.json
> -      "integrity": "sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==",
хм, я не добавлял код в package-lock.json, не знаю что это..

2021-12-16 19:00 UTC, dwin199601 commented on src/app/App.css
> +  transition-property: font-size;
благодарю

2021-12-16 23:35 UTC, merged